# Generated by Django 2.1.2 on 2018-10-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrecord',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='webpage',
            options={'ordering': ['-id']},
        ),
    ]
