# Generated by Django 2.1.2 on 2018-10-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
    ]
